export const REQUEST_CONTACTS = 'REQUEST_CONTACTS';
export const LOAD_CONTACTS = 'LOAD_CONTACTS';
export const SHOW_ERROR = 'SHOW_ERROR';
export const TOGGLE_FAVORITE = 'TOGGLE_FAVORITE';
export const DELETE_CONTACT = 'DELETE_CONTACT';
export const ADD_CONTACT = 'ADD_CONTACT';
export const EDIT_CONTACT = 'EDIT_CONTACT';

export const UPDATE_SNACKBAR = 'UPDATE_SNACKBAR';
